services:
  postgres:
    image: postgres:16-alpine
    container_name: notifyhub-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-notifyhub}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-notifyhub_local_password}
      POSTGRES_DB: ${POSTGRES_DB:-notifyhub}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: notifyhub-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: notifyhub-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-notifyhub}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-notifyhub_local_password}
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT:-15672}:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redpanda:
    image: redpandadata/redpanda:v24.2.7
    container_name: notifyhub-redpanda
    profiles: ["kafka"]
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "1"
      - --memory
      - 1G
      - --reserve-memory
      - 0M
      - --node-id
      - "0"
      - --check=false
      - --kafka-addr
      - INTERNAL://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr
      - INTERNAL://redpanda:9092,OUTSIDE://localhost:19092
    ports:
      - "${KAFKA_PORT:-19092}:19092"
      - "${REDPANDA_ADMIN_PORT:-19644}:9644"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: notifyhub-mailhog
    ports:
      - "${MAILHOG_SMTP_PORT:-1025}:1025"
      - "${MAILHOG_UI_PORT:-8025}:8025"

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: notifyhub-prometheus
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    image: grafana/grafana:11.2.0
    container_name: notifyhub-grafana
    ports:
      - "${GRAFANA_PORT:-3000}:3000"
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  grafana_data:
  redpanda_data:
